# Im Kontakt mit Trainierenden
Eine große Schwierigkeit für viele Trainer\*innen ist es, überhaupt an Klien\*innen zu kommen. Viele Kolleg\*innen mit denen ich in den letzten Jahren gesprochen habe beschreiben eine ähnliche Situation. Gerade am Anfang ist es schwer, an Kund\*innen zu kommen. Je mehr Menschen man jedoch schon betreut hat und desto mehr man sich dadurch einen Namen innerhalb eines Personenkreises gemacht hat, desto einfacher wird es. Wie dieser Personenkreis entsteht ist nebensächlich. Er kann aus losen Verbindungen im Internet oder aus einer örtlichen Gemeindschaft enstehen. Es wird häufig empfohlen, eine konkrete Zielgruppe zu bedienen. So soll dieser Prozess beschleunigt werden. Außerdem eignet man sich einen gewissen Expert\*innen-Status an.

Im direkten Kontakt mit (potentiellen) Klient\*innen sollte ein paar Grundregeln befolgt werden. Ein professionelles Auftreten und Handeln sollte zu jeder Zeit bewahrt werden. Einige Trainer\*innen traineren beispielsweise selbst in Trainingsbereichen in denen auch ihre (potentiellen) Klient\*innen trainieren. Hier sollte man sich zumindest an die geltenden Trainings-Etiketten halten. Es kann sein, dass du als Trainer\*in auch mehr von anderen Personen beim Training beobachtet wirst. Aus vorbildlichem Handlen und guter Trainingsform lassen sich Kontakte leichter herstellen. Gleichzeitig kann diese Situation natürlich auch Druck auslösen. Manche Trainer\*innen ziehen es daher auch vor das eigene Training in einem ungestörten Bereich abzuhalten.
Als Trainer\*in solltest du hier einfach achtsam bleiben. Was strahlst du im Trainingsbereich aus? Unterstützt dein Verhalten und dein Auftreten ein wohlwollendes Kima? Achtest du auf Hygiene, Ordnung und Sauberkeit? Spiegelt dein eigenes Training das wieder, was du auch deinen (potentiellen) Klient\*innen empfiehlst (= Authentizität)? Fühlst du dich persönlich wohl in dieser Doppelrolle, wenn du von anderen beobachtet wirst? Wie wirkt sich das auf dein Trainingsverhalten aus? 

# Umfeldanalyse Trainingsort
Wie bereits besprochen, können viele verschiedene Trainingsorte für PC gewählt werden. Dies reichen von eigenen Trainingsräume der Trainer\*innen, über öffentliche Outdoor-Anlagen, das Wohnzimmer der Klient\*innen bis hin zur Einmiete in fremden Studios.
Vor dem Training mit deinen Klient\*innen solltest du dich in jedem Fall zu Punkten der Sicherheit, aber auch der üblichen Gepflogenheiten des Trainingsort (Etikette) informieren. Wenn du neu in Trainingsbereichen bist, sollst du dir Zeit nehmen, um dir noch vor der Einheit die Einrichtung anzusehen. Dir sollte klar sein wo du welchen Trainingsabschnitt oder welche Übung machen kannst. Außerdem sollte dir bekannt sein, wo der Erste-Hilfe Koffer und der Defibrillator sind. 
Spezifische Punkte, die du prüfen solltest:
* Mache dir einen Überblick, wo du welche Übung oder welchen Trainingsabschnitt am Besten durchführen kannst?
* Ist das Equipment gepflegt und sicher?
  Überprüfe besonders Kabel, Karabiner sowie die Oberfläche an Outdoor-Equpiment
* Wo befindet sich der nächste Defibrillator und Erste-Hilfe Koffer?
* Wenn du Outdoor trainierst, solltest du immer eine zuckerhaltiges Getränk oder ein Kohlehydrate-Gel mitführen.
