# Kontaktaufnahme und Erstgespräch

Eine große Schwierigkeit für viele Trainer\*innen ist es, überhaupt an Klien\*innen zu kommen. Viele Kolleg\*innen mit denen ich in den letzten Jahren gesprochen habe beschreiben eine ähnliche Situation. Gerade am Anfang ist es schwer, an Kund\*innen zu kommen. Je mehr Menschen man jedoch schon betreut hat und desto mehr man sich dadurch einen Namen innerhalb eines Personenkreises gemacht hat, desto einfacher wird es. Wie dieser Personenkreis entsteht ist nebensächlich. Er kann aus losen Verbindungen im Internet oder aus einer örtlichen Gemeindschaft enstehen. Es wird häufig empfohlen, eine konkrete Zielgruppe zu bedienen. So soll dieser Prozess beschleunigt werden. Außerdem eignet man sich einen gewissen Expert\*innen-Status an.

Im direkten Kontakt mit (potentiellen) Klient\*innen sollte ein paar Grundregeln befolgt werden. Ein professionelles Auftreten und Handeln sollte zu jeder Zeit bewahrt werden. Einige Trainer\*innen traineren beispielsweise selbst in Trainingsbereichen in denen auch ihre (potentiellen) Klient\*innen trainieren. Hier sollte man sich zumindest an die geltenden Trainings-Etiketten halten. Es kann sein, dass du als Trainer\*in auch mehr von anderen Personen beim Training beobachtet wirst. Aus vorbildlichem Handlen und guter Trainingsform lassen sich Kontakte leichter herstellen. Gleichzeitig kann diese Situation natürlich auch Druck auslösen. Manche Trainer\*innen ziehen es daher auch vor das eigene Training in einem ungestörten Bereich abzuhalten.
